apiVersion: v1
kind: Service
metadata:
  name: spring-ex-service
  annotations:                                        # ← ADD THIS BLOCK
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/job: "spring-ex1"
spec:
  selector:
    app: spring-ex
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort